
version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      # specify the version you desire here
      - image: circleci/node:7

    steps:
      - checkout
      - run: npm install
      - run: npm run build